Deprected explode router
mageplaza/magento-2-blog pull request #343
Opened 2022-06-29 14:33 UTC by ishiekh-dev

[php 8.1 - explode(): Passing null to parameter #2 ($string) of type string is deprecated]
so i used null coalescing operator to avoid that error

2022-07-25 13:07 UTC, zenfork commented on Controller/Router.php
> +        $ids = explode('/', $identifier ?? '');
```suggestion
        $routePath = explode('/', $identifier ?? '');
```

2022-07-25 15:56 UTC, zenfork commented on Block/Listpost.php
> +            $perPageValues = explode('/', $perPageValues ?? '');
```suggestion
            $perPageValues = explode(',', $perPageValues ?? ''); 
```

2022-07-25 15:57 UTC, zenfork commented on Block/Listpost.php
> +            foreach (explode('/', trim($description) ?? '') as $value) {
```suggestion
            foreach (explode('\n', trim($description) ?? '') as $value) {
```

2022-07-25 15:59 UTC, zenfork commented on Block/Adminhtml/Category/Tree.php
> +        $storeIds = $node->getStoreIds() ? explode('/', $node->getStoreIds() ?? '')   : [];
```suggestion
        $storeIds = $node->getStoreIds() ? explode(',', $node->getStoreIds() ?? '')   : [];
```

2022-07-25 16:08 UTC, zenfork requested changes

2022-07-25 16:08 UTC, zenfork commented on Block/Adminhtml/Post/Edit/Tab/Renderer/Category.php
> +            $values = explode('/', $values ?? '');
```suggestion
            $values = explode(',', $values ?? '');
```

2022-07-25 16:08 UTC, zenfork commented on Block/Adminhtml/Post/Edit/Tab/Renderer/Tag.php
> +            $values = explode('/', $values ?? '');
```suggestion
            $values = explode(',', $values ?? '');
```

2022-07-25 16:08 UTC, zenfork commented on Block/Adminhtml/Post/Edit/Tab/Renderer/Topic.php
> +            $values = explode('/', $values ?? '');
```suggestion
            $values = explode(',', $values ?? '');
```

2022-07-25 16:08 UTC, zenfork commented on Controller/Router.php
> +        $ids = explode('/', $identifier ?? '');
```suggestion
        $routePath = explode('/', $identifier ?? '');
```

2022-07-27 15:50 UTC, Leobaillard commented
@zenfork Thanks for the PR, I need this for a project (2.4.4/PHP8.1) and I'm using your PR as a composer patch to make it work. Unfortunately, the suggested change that you made in `Controller/Router.php` by renaming `$ids` to `$routePath` is needed for it to work and it is not included in the Github patch version of the PR. Could you validate your own suggestion so that it can be used while the PR gets approved by the plugin's author? Thanks a lot!

2022-07-27 16:52 UTC, zenfork approved these changes

2022-08-29 12:26 UTC, Leobaillard commented
Looks like approving the changes does not change the auto diff patch. @ishiekh-dev could you maybe include the suggestions to your PR so that the diff gets updated? Thanks!

2022-09-07 08:14 UTC, Leobaillard commented
Ping @ishiekh-dev ?

2022-11-09 15:13 UTC, KhietNguyen83 commented
Hi ,
Thanks for your contribution.
We have updated and released a new version that solves this problem.
Thank you very much!

2022-11-09 15:13 UTC, closed without merging